name : deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  AUTO_DEPLOY:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Run Script in Server
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_KEY }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          port: ${{ secrets.PORT }}
          script: |
            whoami
            cd /home/ubuntu/discord_playground
