name: deploy

on:
  push:
    paths-ignore: ['*.md', '.gitignore', '.eslintrc', '.prettierrc']
    branches: [main]

jobs:
  AUTO_DEPLOY:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run Script in Server
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_KEY }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          port: ${{ secrets.PORT }}
          script: |
            cd discord_playground
            git fetch origin main
            git rebase FETCH_HEAD
            npm run build
            npx prisma generate
            pm2 kill
            pm2 start node ./dist/main.js
            cd bot
            node deploy-commands.js
            pm2 start node bot-main.js
            whoami
