name : deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  AUTO_DEPLOY:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Run Script in Server
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_KEY }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          port: ${{ secrets.PORT }}
          script: |
            cd discord_playground
            git fetch origin main
            git rebase FETCH_HEAD
            npm run build
            pm2 kill
            node ./bot/deploy-commands.js
            pm2 start node ./dist/main.js
            pm2 start node ./bot/bot-main.js
            whoami
