name: Deploy to Amazon ECS

on:
  push:
    branches:
      - main

jobs:
  SSH:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Run scripts in Server
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_KEY }}
          host: ${{ secrets.HOST }}
          username: ${{ ubuntu }}
          script: |
            cd discord_playground
            git fetch origin main
            git rebase FETCH_HEAD
            npm run build
            cd dist
            pm2 start node main.js
            cd ..
            cd bot
            node deploy-commands.js
            pm2 start node bot-main.js
